# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 00:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities_light', '0003_auto_20170909_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEspecie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nombre_cientifico', models.CharField(max_length=60)),
                ('desc_corta', models.CharField(max_length=150)),
                ('desc_larga', models.CharField(max_length=500)),
                ('foto', models.ImageField(null=True, upload_to='images')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatalogoApp.CategoriaEspecie')),
            ],
        ),
        migrations.CreateModel(
            name='TaxonomiaEspecie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to='images/user')),
                ('comentario_interes', models.CharField(max_length=1000)),
                ('auth_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.City')),
                ('pais_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country')),
            ],
        ),
        migrations.AddField(
            model_name='especie',
            name='taxonomia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatalogoApp.TaxonomiaEspecie'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='especie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatalogoApp.Especie'),
        ),
    ]
